### PR TITLE
SPNPTL-105 Note last name validation workaround

### PR DESCRIPTION
**Pull request by apetro**
( [SPNPTL-105][] , see also [SPNPTL-104][] for context.)

There's a bug where if a person

1. Sets a preferred last name (e.g., to get O365 to stop shouting)
2. Changes system-of-record last name (e.g., following an unhappy divorce, or upon a happy marriage)
3. Attempts to update preferred last name to reflect the new system-of-record last name

the preferred last name validation logic fails because it tries to enforce allowable preferred last name changes comparing with *the current preferred last name* rather than comparing with the new system-of-record last name.

This is causing support contacts and is annoying our partners for this self-service tool in MyUW.

The deeper fix is blocked by laying hands on a clean view on current system-of-record last name.

There's a workaround, documented in the KB, of first deleting the preferred name, then waiting, then creating a preferred name anew.

This changeset simply acknowledges this bug in the UI so that affected users can become aware of it and potentially execute the workaround without incurring the support contact.

Nicely, the message only shows to users who are experiencing a preferred last name validation failure and so may be affected by this bug, rather than subjecting all users to this noise.

Before:

status quo

After:

more revised

(revised)

Looks to me like [`header.jsp`'s  `<spring:htmlEscape defaultHtmlEscape="true" />`](https://github.com/UW-Madison-DoIT/StudentPreferredNamePortlet/blob/df9ac54ab1f32cf07bf00a242064a9e4d6fe8c9d/student-preferred-name-portlet-webapp/src/main/webapp/WEB-INF/jsp/header.jsp#L26) means that [`viewPage.jsp`'s ` *<spring:message code='error.lastNameWeirdLogicError'/>`](https://github.com/UW-Madison-DoIT/StudentPreferredNamePortlet/blob/df9ac54ab1f32cf07bf00a242064a9e4d6fe8c9d/student-preferred-name-portlet-webapp/src/main/webapp/WEB-INF/jsp/viewPage.jsp#L103) will escape out HTML if the message tries to include HTML, so going with 

`Learn more in the KB at https://kb.wisc.edu/myuw/page.php?id=58831 .` 

rather than something like 

`Learn more <a href=" https://kb.wisc.edu/myuw/page.php?id=58831">in the KB</a>.`.

This allows this change to be purely in `messages.properties`, and thus suitable for application to e.g. production without cutting a `StudentPreferredNamePortlet` release. :smile: .

[SPNPTL-104]: https://jira.doit.wisc.edu/jira/browse/SPNPTL-104
[SPNPTL-105]: https://jira.doit.wisc.edu/jira/browse/SPNPTL-105

### CODE REVIEW

**Comment by timlevett** [comment]
This error seems a bit long, some people may see this as noise. Maybe something like: "For last name you may only change capitalization, spacing, and hypens. If you recently changed your last name read <kb-article>".  

The KB article would have the explanation.

**Comment by vertein** [comment]
I like the adding of messaging to help the user out.

I do like the Material design standards for writing for [language](https://www.google.com/design/spec/style/writing.html#writing-language) and [tone] (https://www.google.com/design/spec/style/writing.html#writing-tone).  Examples are positive tone, essential, and concise.  I'm not a text expert, and I am open to any suggestions, but maybe something like this: 

`Change capitalization, spacing, apostrophes, and hyphens in your preferred last name.  Learn more in the [KB] (kb link here).`

Nice thinking on expanding error message.  I do think that this will help us, the helpdesk, and the users.

**Comment by apetro** [comment]
The context here is that this tool is bugged. Users may attempt a last name change that ought to succeed by policy and that nonetheless fails. Fixing the bug will be great; in the meantime I think we need a UI that acknowledges the bug.

So, 

> Change capitalization, spacing, apostrophes, and hyphens in your preferred last name. Learn more in the KB.

seems like a great steady state message once that bug is fixed, but so long as it's bugged, it seems insufficient.  The message isn't just that you could learn more, it's that what you're going to learn if you go learn more is that there's a bug that may be causing the validation failure and that there's a workaround.

> For last name you may only change capitalization, spacing, and hypens. If you recently changed your last name read kb-article

at least nods at the bug.

Dunno. Are users best served linked to an external article about a workaround, or are they best advised of the workaround right where they need to execute it?

**Comment by timlevett** [comment]
An additional click to more details on an edge case seems like an appropriate solution. Its hard to say "everyone that hits this error is hitting this bug" because that is simply not true. No data to back this up really. What I would suggest is run it by Keir and Jess. Since they have been coming up with our text lately.

**Comment by vertein** [comment]
I still feel strongly about Material design, but if we really wanted to throw a work around message in the error text, I would still follow some of the patterns.  I barely know what the word system-of-records means, so I would not use that word.  Maybe something like:

**Comment by timlevett** [comment]
I second :+1:  @vertein 's latest

**Comment by keirserrie** [comment]
I'm okay with this running a bit long since it only appears as an error for those with a problem, but it's still a little TL/DR.  Can we direct them to the fix rather than saying they "may have to" do it?

You may only change capitalization, spacing, apostrophes, and hyphens in your preferred last name. If your legal last name has changed, delete your preferred last name, wait 24 hours, then enter the new name. Learn more in the KnowledgeBase: (kb link here)

**Comment by apetro** [comment]
Going with @keirserrie 's text, in order to un-block this.  This is a temporary fix, after all, with hope for correcting the preferred last name validation logic for this case soon.

I do like what @vertein had to say about Material Design and what it guides as to text.

**Comment by apetro** [comment]
(Looks like the `?` in the message broke this portlet on test.my. Trying replacing with a go.wisc URL.)

**Pull request merged**
