### PR TITLE
SPNPTL-87 : Clean up preferred last name

### PR DESCRIPTION
**Pull request by timlevett**
Based on [this](https://docs.google.com/a/wisc.edu/file/d/0BxQTQDkqSSRuMjN1V0h0VU1pa1k/edit), I did this.

#### Universality
http://goo.gl/mZAGbT

http://goo.gl/TDYzQj

#### Bucky

http://goo.gl/Go11FY

http://goo.gl/AiojSy

http://goo.gl/wUphHR

### CODE REVIEW

**Comment by jhanstra** [comment]
Coding during meetings, nicee :+1:

**Comment by timlevett** [comment]
You know how I roll.

**Comment by apetro** [comment]
Looks great -- let's get this up on predev and do a quick show-and-tell with Mark Treiber.

**Comment by keirserrie** [comment]
Great. Possible to make text field labels not italic?

**Comment by timlevett** [comment]
Yeah, i can do that.

**Comment by keirserrie** [comment]
and screenshot of error msg too please

**Comment by timlevett** [comment]
http://goo.gl/zt8fC5

Error message

**Comment by timlevett** [comment]
No more sarcastic labels
http://goo.gl/Mwa180

**Comment by keirserrie** [comment]
thx on labels

what is effort level on this for error msg:

untitled-6

**Comment by timlevett** [comment]
@keirserrie - that would be neat, but that would be a different type of validation. Would be pretty high

**Pull request merged**
